### ISSUE TITLE
7z解压不了

### ISSUE THREAD

**Issue by christan-duplicate** [ldqk/Masuit.Tools#59]
```
SevenZipCompressor.Decompress(@"D:\Download\test.7z", @"D:\Download\");
Unhandled exception. System.InvalidOperationException: Cannot determine compressed stream type.  Supported Reader Formats: Zip, GZip, BZip2, Tar, Rar, LZip, XZ
   at SharpCompress.Readers.ReaderFactory.Open(Stream stream, ReaderOptions options)
   at Masuit.Tools.Files.SevenZipCompressor.Decompress(String compressedFile, String dir, Boolean ignoreEmptyDir) in \ldqk\Masuit.Tools\Masuit.Tools.Abstractions\Files\SevenZipCompressor.cs:line 122
```

**Comment by ldqk** [comment]
还是尽量使用Zip, GZip, BZip2, Tar, Rar, LZip, XZ格式吧，7z过于复杂：https://github.com/adamhathcock/sharpcompress#recommended-formats

**Comment by ldqk** [comment]
SharpCompress将来会支持7z的

**Comment by christan-duplicate** [comment]
做下判断：用 ArchiveFactory 就可以支持7z了

**Comment by ldqk** [comment]
感谢提示，现已支持7z文件，使用最新包即可
