### ISSUE TITLE
MultiThreadDownloader 出现 System.IO.IOException 和 System.InvalidOperationException 异常

### ISSUE THREAD

**Issue by cnwanghao** [ldqk/Masuit.Tools#6]
使用的版本:nuget 2.2.7.3
.net框架: .net framework 3.7

MultiThreadDownloader  这个类抛出异常

```
System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 System.Linq.Enumerable.Sum(IEnumerable`1 source)
   在 Masuit.Tools.Net.MultiThreadDownloader.get_TotalBytesReceived() 位置 D:\MyCode\Masuit.Tools\Masuit.Tools\Net\MultiThreadDownloader.cs:行号 64
   在 Masuit.Tools.Net.MultiThreadDownloader.UpdateProgress() 位置 D:\MyCode\Masuit.Tools\Masuit.Tools\Net\MultiThreadDownloader.cs:行号 198
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
```
出现这个异常后文件能正常下载完成,异常出现在文件合并的时候

```

System.IO.IOException
  HResult=0x80070020
  Message=文件“C:\Users\cnwan\AppData\Local\Temp\2d54b17c-61f6-45c2-9357-0c9100f26fa2”正由另一进程使用，因此该进程无法访问此文件。
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Masuit.Tools.Net.MultiThreadDownloader.MergeParts()
   at Masuit.Tools.Net.MultiThreadDownloader.temp_DownloadPartCompleted(Object sender, EventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
这个异常出现在下载过程之中,文件不能下载完成

**Comment by ldqk** [comment]
感谢反馈，未及时查看issue，抱歉，该问题是由于最后合并时删除临时文件没有做容错处理，最新包已修正该问题
