### ISSUE TITLE
[BUG]SevenZipCompressor解压7z压缩包报异常

### ISSUE THREAD

**Issue by dzx815** [ldqk/Masuit.Tools#61]
**bug描述**
SevenZipCompressor解压7z压缩包报异常，压缩包是通过7z官方安装的图形化工具压缩的

![image](https://user-images.githubusercontent.com/15151459/149258052-a6fd935d-e9cf-40d5-82e3-32911715e805.png)

**是哪个函数出现了bug**
SevenZipCompressor.Decompress

**异常堆栈信息**
![image](https://user-images.githubusercontent.com/15151459/149258244-88756b9c-1eef-4f56-8abd-b750e1e71144.png)

**函数入参**
SevenZipCompressor.Decompress(@"E:\Download\11.7z", @"E:\Download");

**期望的结果或输出**
正常解压和压缩7z压缩包

**使用环境:**
 - OS: [WIN10]
 - Version [2.4.5.5]
 - .NET Runtime [4.8]

**您的一些其他的想法**
无

**Comment by ldqk** [comment]
压缩包是否存在加密的情况？程序不支持加密的压缩包的哦。

**Comment by dzx815** [comment]
没有加密，调用7z.exe可以正常解压缩的

**Comment by ldqk** [comment]
已找到原因了，.NET Framework版本的包还未修正这个bug，稍后在nuget商店安装2.4.7.1-beta版本的包可解

**Comment by dzx815** [comment]
再问一下，这个可以直接压缩成7z格式吗？
还是只是改了后缀名而已？

**Comment by dzx815** [comment]
更新4.7.1以后，还是不行，一样的报异常

**Comment by ldqk** [comment]
支持的，压缩时文件后缀设置为7z，然后有个可选参数ArchiveType，是个枚举类型，传ArchiveType.SevenZip即可

**Comment by dzx815** [comment]
压缩成7z报错
代码
List<string> aa = new List<string> { @"E:\Download\1.txt" };
            SevenZipCompressor.Zip(aa, @"E:\Download\2.7z", "", SharpCompress.Common.ArchiveType.SevenZip);


异常
System.NotSupportedException
  HResult=0x80131515
  Message=Cannot create Archives of type: SevenZip
  Source=SharpCompress
  StackTrace:
   at SharpCompress.Archives.ArchiveFactory.Create(ArchiveType type)
   at Masuit.Tools.Files.SevenZipCompressor.CreateZipArchive(List`1 files, String rootdir, ArchiveType archiveType)
   at Masuit.Tools.Files.SevenZipCompressor.Zip(List`1 files, String zipFile, String rootdir, ArchiveType archiveType)
   at DirRename.Window1.button1_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProvid

**Comment by ldqk** [comment]
那就是SharpCompress还是没有支持真7z的压缩

**Comment by dzx815** [comment]
.net frame更新后还是不能解压缩7Z。

.net core可以正常解压缩7Z，但是当文件存在时，解压缩报错，建议增加选项是否覆盖

**Comment by ldqk** [comment]
.NET Framework版本的包经测试是没问题的，确保下是否是没有安装到最新的包；真7z的支持还是得等SharpCompress的更新

**Comment by dzx815** [comment]
![image](https://user-images.githubusercontent.com/15151459/149275743-1050ccb1-2434-4fb3-a545-01e4eafd5e2f.png)

确定是最新的包了。

我已经用SharpCompress实现了7z解压缩，并且可以直接覆盖旧文件，所以这个bug先关了。
![image](https://user-images.githubusercontent.com/15151459/149275953-b664ba11-4787-436e-b795-ec0bf865bd69.png)
